# Generated by Django 2.2.3 on 2020-02-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200217_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='lda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('score', models.FloatField()),
            ],
        ),
    ]
