# Generated by Django 2.2.3 on 2020-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfidfsc',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='urls',
            name='score',
            field=models.FloatField(),
        ),
    ]
